FROM python:3.9-alpine

WORKDIR /app
COPY . /app/

RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

CMD ["python", "bot.py"]
