FROM python:3.11-slim

RUN apt-get update && apt-get install -y gcc libffi-dev

WORKDIR /app
COPY . /app

# Удаляем кеш перед установкой зависимостей
RUN rm -rf /root/.cache/pip
RUN pip install --upgrade pip wheel setuptools
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "bot.py"]
